// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xikepdunxxhchuxdqsdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpa2VwZHVueHhoY2h1eGRxc2RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5NjU0NDIsImV4cCI6MjA4NDU0MTQ0Mn0.LGPa1PjL8tC9budM2qbhMrXSAamG62wiQWzmkt4nWBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);